version: 2
jobs:
  my_ci_and_cd:
    machine: true
    steps:
    - run: |
        sudo apt update && sudo apt install sshpass -y
    - run: "sshpass -p $spineor ssh spineor@192.168.0.101 'ls -ltr' \n"
    
  workflows:
   version: 2
    rolling_update:
      jobs:
    - my_ci_and_cd:
        filters:
          branches:
            only:
            - master

